"""
PDF export router — generates PDF for reports using weasyprint.
"""
import json
import logging
import os
import tempfile
from datetime import datetime
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse

import db as db_service
from middleware import get_current_user_optional

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/export", tags=["Export"])


def _generate_pdf_html(title: str, content: str, meta: Optional[dict] = None) -> str:
    meta_html = ""
    if meta:
        meta_html = "<div class='meta'>" + "".join(
            f"<p><strong>{k}:</strong> {v}</p>" for k, v in meta.items()
        ) + "</div>"

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  @page {{ margin: 2cm; @bottom-center {{ content: counter(page) "/" counter(pages); font-size: 9px; color: #888; }} }}
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11pt; line-height: 1.6; color: #222; }}
  h1 {{ font-size: 20pt; color: #1a56d9; margin-bottom: 0.25cm; }}
  h2 {{ font-size: 15pt; color: #333; margin-top: 1cm; border-bottom: 1px solid #ddd; padding-bottom: 3px; }}
  h3 {{ font-size: 12pt; color: #444; margin-top: 0.5cm; }}
  .meta {{ background: #f5f7fa; padding: 0.5cm; border-radius: 4px; margin: 0.5cm 0; font-size: 10pt; }}
  .meta p {{ margin: 2px 0; }}
  table {{ width: 100%; border-collapse: collapse; margin: 0.5cm 0; font-size: 10pt; }}
  th {{ background: #f0f2f5; padding: 6px 8px; text-align: left; border: 1px solid #ddd; font-weight: 600; }}
  td {{ padding: 6px 8px; border: 1px solid #ddd; }}
  pre {{ background: #f8f9fa; padding: 0.3cm; border-radius: 3px; font-size: 9pt; overflow-x: auto; }}
  .footer {{ margin-top: 1cm; font-size: 8pt; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 0.3cm; }}
</style>
</head>
<body>
<h1>{title}</h1>
{meta_html}
<div class='content'>{content}</div>
<div class='footer'>Generated by Wens Financial Report Service on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</div>
</body>
</html>"""


@router.get("/report/{report_id}/pdf")
async def export_report_pdf(
    report_id: int,
    current_user: dict = Depends(get_current_user_optional),
):
    pool = await db_service.get_pool()
    row = await pool.fetchrow("SELECT * FROM generated_reports WHERE id = $1", report_id)
    if not row:
        raise HTTPException(404, "Report not found")

    report = db_service._serialize_row(row)
    content_html = report.get("report", "").replace("\n", "<br>")
    meta = {
        "Model": report.get("model", "N/A"),
        "Tokens Used": report.get("tokens_used", "N/A"),
        "Query": report.get("query", "")[:200],
    }

    html = _generate_pdf_html(f"Financial Report #{report_id}", content_html, meta)

    try:
        from weasyprint import HTML
        fd, path = tempfile.mkstemp(suffix=".pdf")
        os.close(fd)
        HTML(string=html).write_pdf(path)
        filename = f"report_{report_id}_{datetime.utcnow().strftime('%Y%m%d')}.pdf"
        return FileResponse(path, media_type="application/pdf", filename=filename,
                            headers={"Content-Disposition": f"attachment; filename={filename}"})
    except ImportError:
        raise HTTPException(501, "PDF generation requires weasyprint — install with: pip install weasyprint")
    except Exception as e:
        raise HTTPException(500, f"PDF generation failed: {e}")


@router.get("/generated/{report_id}/pdf")
async def export_generated_pdf(
    report_id: int,
    current_user: dict = Depends(get_current_user_optional),
):
    return await export_report_pdf(report_id, current_user)
